### ISSUE TITLE
Adding "Em" on link's end

### ISSUE THREAD

**Issue by maverick74** [nekoziroo/Text-Link-webext#3]
On links starting with "www." (such as www.linksoflondon.com/gb-en/women/bracelets ) the addon is adding an "Em" at the end of the URL, transforming this 

_www.linksoflondon.com/gb-en/women/bracelets_ 

into this 

**www.linksoflondon.com/gb-en/women/braceletsEm**

**Comment by nekoziroo** [comment]
What is Em?

**Comment by maverick74** [comment]
no idea of what it is... 
but links are opening with that two extra letters added at the end of any URL that starts with "www."

if a link is www.MyDogEatMyLunch.com the TextLink will try to open www.MyDogEatMyLunch.comEm

it adds the letters "Em" to all links started with www.

**Comment by nekoziroo** [comment]
On my PC "Em" was not added to the end of the URL.
Firefox 56.0 64bit
Firefox Developer Edition 57.0b6 64bit
windows 10 64bit
Which website does the link have?

**Comment by maverick74** [comment]
Actually, let me correct myself: now, it's apparently doing it with all links...

try this:

**First test:**
go to: https://www.google.com/search?dcr=0&source=hp&q=Links+-+Twibright+Labs&oq=Links+-+Twibright+Labs&gs_l=psy-ab.3...3087.3087.0.4009.3.2.0.0.0.0.137.137.0j1.2.0....0...1.1.64.psy-ab..1.0.0.0...102.1IhlS0c3czo

on the first link, double click the green text!

**My result:** it opens http://links.twibright.com/Em

---

**Second Test:**

Go to: https://www.google.com/search?safe=active&dcr=0&q=Links+-+Compete+-+Qren&oq=Links+-+Compete+-+Qren&gs_l=psy-ab.3...178237.178237.0.179269.1.1.0.0.0.0.220.220.2-1.1.0....0...1.1.64.psy-ab..0.0.0....0.lsLy3TB4mso

on the first link, double click the green text!

**My result:** it opens http://www.pofc.qren.pt/linksEm

---

**Third test:**
Go to: https://www.google.com/search?safe=active&dcr=0&q=Links+online+du%C4%87an&oq=Links+online+du%C4%87an&gs_l=psy-ab.3..0i22i30k1l3.218883.218883.0.219734.1.1.0.0.0.0.217.217.2-1.1.0....0...1.1.64.psy-ab..0.1.216....0.28Othw3vwBo


on the first link, double click the green text!

**My result:** it opens https://www.links.hr/hr/em

---

I'm on Linux with Firefox 56.0 (64bit)

Maybe it's another addon... but i'm really having this results

**Comment by nekoziroo** [comment]
I set the language of Firefox to English. Then "CachedSimilar" was added to the end of the URL.
http://links.twibright.com/CachedSimilar

**Comment by nekoziroo** [comment]
Fixed in version 1.0.4.
Try it to work.

**Comment by maverick74** [comment]
Problem solved!! Thanks.

Still, URL's such as google.es still do not work (google.com does, however). 

Should i open a new bug for this?

**Comment by nekoziroo** [comment]
yes.
